# Generated by Django 3.0.5 on 2021-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='userName', max_length=32)),
                ('password', models.CharField(default='000000', max_length=50)),
                ('major', models.CharField(default='undefined', max_length=20)),
                ('email', models.CharField(default='emailaddress', max_length=50)),
                ('phoneNumber', models.CharField(default='phonenumber', max_length=32)),
            ],
        ),
    ]
